### ISSUE TITLE
Balance incorrectly shows zero

### ISSUE THREAD

**Issue by Grimm2017** [CityOfZion/neon-wallet#319]
Blockchain explorer shows correct NEO shares at my public address but the wallet (version 0.0.7) shows zero balance and no transactions.  When NEON opens it also shows the block number as zero.

The wallet worked fine for two days.  The problem started today when I opened the wallet.

**Comment by Jacko3816** [comment]
I have this exact issue also.

**Comment by stephenkorsman** [comment]
Same issue.  On Fridays I check my wallets, and then check for updates.  Neon never loaded any balances.  I checked for an update, and updated to 0.0.7.  Still no balance for either NEO or GAS.  Using 64 bit linux version.

**Comment by dwilps33** [comment]
Same issue as well. Briefly had a visual of my past transactions (balance was still 0), but that is gone again. Everything is there when I check the blockchain explorer though.

**Comment by madDARKO** [comment]
same problem, shows all zero, but when i check with my public adress it shows how it should be?
whats happening here

**Comment by dwilps33** [comment]
Just posted on City of Zion Twitter account - "Neon Wallet API is currently down. Please use blockchain explorers to verify your wallet balance. Do not worry, your tokens will be safe in Neon, especially if you are using Ledger Nano S. We sincerely apologise for this inconvenience."

**Comment by arenstar** [comment]
@dwilps33 how do you mean "safe in Neon" especially if you are using Ledger Nano S? 
Should i be concerned if im not using Ledger Nano S?

Could you please explain the issue in some detail!

**Comment by warren8tor** [comment]
My balance shows zero also

**Comment by wowology** [comment]
I have same issue. The blockchain shows the correct amount on Neotracker, but in wallet all is zero.  Yesterday everything showed correctly. Are they fixing this issue?

**Comment by wowology** [comment]
everything is solved again, balance is back!

**Comment by Jacko3816** [comment]
The problem has resolved itself. Everything is as it should be now!

**Comment by evgenyboxer** [comment]
I'm currently working on the connectivity notifications, so the next version will have a fix for this.

**Comment by msrinu143** [comment]
I just checked mine, it is still showing zero balance. I really feel  terrible now!
Please some advice!

**Comment by Dooctoore** [comment]
mine is also zero balance guys. however when i check on blockchain may balance can bee seen correctly.how could you fix that problem . I feel terrible too 👎
